In [1]:
import numpy as np
import os
import warnings
import gc

import sys
sys.path.append('./')
from libs.data_utils import encode_categorical, extract_num, reshape_sales, merge_calendar, merge_prices, reduce_mem_usage
from libs.feature_utils import add_demand_features, add_price_features, add_time_features

import pandas as pd
from pandas.plotting import register_matplotlib_converters
import numpy as np
import tables
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

# Read Data
INPUT_DIR = "../input/m5-forecasting-accuracy"
print("Reading files...")
calendar = pd.read_csv(f"{INPUT_DIR}/calendar.csv").pipe(reduce_mem_usage)
prices = pd.read_csv(f"{INPUT_DIR}/sell_prices.csv").pipe(reduce_mem_usage)
sales = pd.read_csv(f"{INPUT_DIR}/sales_train_validation.csv",).pipe(reduce_mem_usage)
submission = pd.read_csv(f"{INPUT_DIR}/sample_submission.csv").pipe(reduce_mem_usage)

NUM_ITEMS = sales.shape[0]
DAYS_PRED = submission.shape[1] - 1

Reading files...

In [12]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 100)

In [2]:
# Encode Categorical
# calendar = encode_categorical(calendar, ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]).pipe(reduce_mem_usage)
sales = encode_categorical(sales, ["item_id", "dept_id", "cat_id", "store_id", "state_id"],).pipe(reduce_mem_usage)
prices = encode_categorical(prices, ["item_id", "store_id"]).pipe(reduce_mem_usage)

# merge tables
data = reshape_sales(sales, submission, DAYS_PRED, d_thresh=1941 - 90)
del sales
gc.collect()

calendar["d"] = extract_num(calendar["d"])
data = merge_calendar(data, calendar)
del calendar
gc.collect()

data = merge_prices(data, prices)
del prices
gc.collect()

data = reduce_mem_usage(data)

# feature engineering
dt_col = "date"

/Users/shukigoto/Documents/git/walmart-compe/libs/data_utils.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evals["id"] = evals["id"].str.replace("_evaluation", "_validation")

agg_df = df.groupby(["state_id", "cat_id","d"])["demand"].mean().reset_index()
df = df.merge(agg_df.groupby(["state_id", "cat_id"]["demand"].transform(lambda x: x.shift(28).rolling(window).mean())),
              on=["state_id", "cat_id"],
              how="left")

In [3]:
data.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,8.26
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,3.97
2,HOBBIES_1_003_CA_1_validation,1439,3,1,0,0,1851,0,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,2.97
3,HOBBIES_1_004_CA_1_validation,1440,3,1,0,0,1851,2,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,4.64
4,HOBBIES_1_005_CA_1_validation,1441,3,1,0,0,1851,0,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,2.88

In [5]:
from tqdm import tqdm
for diff in tqdm([0, 7, 14, 21, 28]):
        shift = 28 + diff
        data[f"demand_shift_t{shift}"] = data.groupby(["id"])["demand"].transform(
            lambda x: x.shift(shift)
        )

100%|██████████| 5/5 [00:52<00:00, 10.45s/it]

In [17]:
data.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd',
       'demand', 'part', 'date', 'wm_yr_wk', 'event_name_1', 'event_type_1',
       'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI',
       'sell_price', 'demand_shift_t28', 'demand_shift_t35',
       'demand_shift_t42', 'demand_shift_t49', 'demand_shift_t56'],
      dtype='object')

In [25]:
agg_list = []
for diff in tqdm([28, 35, 42, 49, 56]):
    agg_list.append(data.groupby(["state_id", "cat_id","d"])[f"demand_shift_t{diff}"].mean().reset_index())

100%|██████████| 5/5 [00:00<00:00,  7.68it/s]

In [27]:
agg_df = agg_list[0]
for i in range(len(agg_list )-1):
    agg_df = agg_df.merge(agg_list[i +1], on=["state_id","cat_id","d"], how="left")

In [30]:
for i in range(4):
    agg_df[f"state_cat_t{28+i*7}/t{35+i*7}"]=agg_df[f"demand_shift_t{28+i*7}"]/agg_df[f"demand_shift_t{35+i*7}"]

In [33]:
agg_df["state_cat_same_dayofweek_4times_mean"]=(agg_df["demand_shift_t28"]+agg_df["demand_shift_t28"]+agg_df["demand_shift_t35"]+agg_df["demand_shift_t42"]) / 4

In [34]:
agg_df.head(50)

,state_id,cat_id,d,demand_shift_t28,demand_shift_t35,demand_shift_t42,demand_shift_t49,demand_shift_t56,state_cat_t28/t35,state_cat_t35/t42,state_cat_t42/t49,state_cat_t49/t56,state_cat_same_dayofweek_4times_mean
0,0,0,1851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,1852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,1853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,1854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,1855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0,0,1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0,0,1857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0,0,1858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0,0,1859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0,0,1860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0,0,1861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0,0,1862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0,0,1863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0,0,1864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0,0,1865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0,0,1866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0,0,1867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0,0,1868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0,0,1869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0,0,1870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0,0,1871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0,0,1872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0,0,1873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0,0,1874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0,0,1875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0,0,1876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0,0,1877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0,0,1878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0,0,1879,1.821329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0,0,1880,1.652053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0,0,1881,1.538448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0,0,1882,1.625609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,0,0,1883,1.859255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0,0,1884,2.426583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,0,0,1885,2.570633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0,0,1886,1.827244,1.821329,NaN,NaN,NaN,1.003248,NaN,NaN,NaN,NaN
36,0,0,1887,1.821155,1.652053,NaN,NaN,NaN,1.102359,NaN,NaN,NaN,NaN
37,0,0,1888,1.700765,1.538448,NaN,NaN,NaN,1.105507,NaN,NaN,NaN,NaN
38,0,0,1889,1.711726,1.625609,NaN,NaN,NaN,1.052975,NaN,NaN,NaN,NaN
39,0,0,1890,1.809325,1.859255,NaN,NaN,NaN,0.973145,NaN,NaN,NaN,NaN
40,0,0,1891,2.471468,2.426583,NaN,NaN,NaN,1.018497,NaN,NaN,NaN,NaN
41,0,0,1892,2.821503,2.570633,NaN,NaN,NaN,1.097591,NaN,NaN,NaN,NaN
42,0,0,1893,2.008177,1.827244,1.821329,NaN,NaN,1.099019,1.003248,NaN,NaN,1.916232
43,0,0,1894,1.892484,1.821155,1.652053,NaN,NaN,1.039167,1.102359,NaN,NaN,1.814544
44,0,0,1895,1.823243,1.700765,1.538448,NaN,NaN,1.072013,1.105507,NaN,NaN,1.721425
45,0,0,1896,1.822373,1.711726,1.625609,NaN,NaN,1.064641,1.052975,NaN,NaN,1.745520
46,0,0,1897,1.888483,1.809325,1.859255,NaN,NaN,1.043750,0.973145,NaN,NaN,1.861387
47,0,0,1898,2.455289,2.471468,2.426583,NaN,NaN,0.993453,1.018497,NaN,NaN,2.452157
48,0,0,1899,2.468337,2.821503,2.570633,NaN,NaN,0.874830,1.097591,NaN,NaN,2.582203
49,0,0,1900,1.923452,2.008177,1.827244,1.821329,NaN,0.957810,1.099019,1.003248,NaN,1.920581

In [23]:
agg_df.head(50)

    state_id  cat_id     d  demand_shift_t28
0          0       0  1851               NaN
1          0       0  1852               NaN
2          0       0  1853               NaN
3          0       0  1854               NaN
4          0       0  1855               NaN
5          0       0  1856               NaN
6          0       0  1857               NaN
7          0       0  1858               NaN
8          0       0  1859               NaN
9          0       0  1860               NaN
10         0       0  1861               NaN
11         0       0  1862               NaN
12         0       0  1863               NaN
13         0       0  1864               NaN
14         0       0  1865               NaN
15         0       0  1866               NaN
16         0       0  1867               NaN
17         0       0  1868               NaN
18         0       0  1869               NaN
19         0       0  1870               NaN
20         0       0  1871               NaN
21         0       0  1872               NaN
22         0       0  1873               NaN
23         0       0  1874               NaN
24         0       0  1875               NaN
25         0       0  1876               NaN
26         0       0  1877               NaN
27         0       0  1878               NaN
28         0       0  1879          1.821329
29         0       0  1880          1.652053
30         0       0  1881          1.538448
31         0       0  1882          1.625609
32         0       0  1883          1.859255
33         0       0  1884          2.426583
34         0       0  1885          2.570633
35         0       0  1886          1.827244
36         0       0  1887          1.821155
37         0       0  1888          1.700765
38         0       0  1889          1.711726
39         0       0  1890          1.809325
40         0       0  1891          2.471468
41         0       0  1892          2.821503
42         0       0  1893          2.008177
43         0       0  1894          1.892484
44         0       0  1895          1.823243
45         0       0  1896          1.822373
46         0       0  1897          1.888483
47         0       0  1898          2.455289
48         0       0  1899          2.468337
49         0       0  1900          1.923452

In [8]:
agg_df["state_cate_window7_mean"] = agg_df.groupby(["state_id", "cat_id"])["demand_shift_t28"].transform(lambda x: x.shift(28).rolling(7).mean())

In [14]:
agg_df.head(40)

    state_id  cat_id     d    demand  window7_mean
0          0       0  1851  1.821329           NaN
1          0       0  1852  1.652053           NaN
2          0       0  1853  1.538448           NaN
3          0       0  1854  1.625609           NaN
4          0       0  1855  1.859255           NaN
5          0       0  1856  2.426583           NaN
6          0       0  1857  2.570633           NaN
7          0       0  1858  1.827244           NaN
8          0       0  1859  1.821155           NaN
9          0       0  1860  1.700765           NaN
10         0       0  1861  1.711726           NaN
11         0       0  1862  1.809325           NaN
12         0       0  1863  2.471468           NaN
13         0       0  1864  2.821503           NaN
14         0       0  1865  2.008177           NaN
15         0       0  1866  1.892484           NaN
16         0       0  1867  1.823243           NaN
17         0       0  1868  1.822373           NaN
18         0       0  1869  1.888483           NaN
19         0       0  1870  2.455289           NaN
20         0       0  1871  2.468337           NaN
21         0       0  1872  1.923452           NaN
22         0       0  1873  1.693633           NaN
23         0       0  1874  1.644746           NaN
24         0       0  1875  1.615866           NaN
25         0       0  1876  1.858038           NaN
26         0       0  1877  2.104036           NaN
27         0       0  1878  2.172756           NaN
28         0       0  1879  1.863953           NaN
29         0       0  1880  1.822373           NaN
30         0       0  1881  1.738866           NaN
31         0       0  1882  1.744259           NaN
32         0       0  1883  2.195372           NaN
33         0       0  1884  2.842380           NaN
34         0       0  1885  2.469729      1.927702
35         0       0  1886  1.708594      1.928547
36         0       0  1887  1.712770      1.952704
37         0       0  1888  1.594468      1.975892
38         0       0  1889  1.729471      1.988195
39         0       0  1890  2.068720      1.981062

In [17]:
from tqdm import tqdm
for window in tqdm([7, 14, 21, 28]):
    agg_df[f"state_cate_mean_window{window}"] = agg_df.groupby(["state_id", "cat_id"])["demand"].transform(lambda x: x.shift(28).rolling(window).mean())

100%|██████████| 4/4 [00:00<00:00, 90.20it/s]

In [19]:
agg_df.head(60)

,state_id,cat_id,d,demand,window7_mean,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28
0,0,0,1851,1.821329,NaN,NaN,NaN,NaN,NaN
1,0,0,1852,1.652053,NaN,NaN,NaN,NaN,NaN
2,0,0,1853,1.538448,NaN,NaN,NaN,NaN,NaN
3,0,0,1854,1.625609,NaN,NaN,NaN,NaN,NaN
4,0,0,1855,1.859255,NaN,NaN,NaN,NaN,NaN
5,0,0,1856,2.426583,NaN,NaN,NaN,NaN,NaN
6,0,0,1857,2.570633,NaN,NaN,NaN,NaN,NaN
7,0,0,1858,1.827244,NaN,NaN,NaN,NaN,NaN
8,0,0,1859,1.821155,NaN,NaN,NaN,NaN,NaN
9,0,0,1860,1.700765,NaN,NaN,NaN,NaN,NaN
10,0,0,1861,1.711726,NaN,NaN,NaN,NaN,NaN
11,0,0,1862,1.809325,NaN,NaN,NaN,NaN,NaN
12,0,0,1863,2.471468,NaN,NaN,NaN,NaN,NaN
13,0,0,1864,2.821503,NaN,NaN,NaN,NaN,NaN
14,0,0,1865,2.008177,NaN,NaN,NaN,NaN,NaN
15,0,0,1866,1.892484,NaN,NaN,NaN,NaN,NaN
16,0,0,1867,1.823243,NaN,NaN,NaN,NaN,NaN
17,0,0,1868,1.822373,NaN,NaN,NaN,NaN,NaN
18,0,0,1869,1.888483,NaN,NaN,NaN,NaN,NaN
19,0,0,1870,2.455289,NaN,NaN,NaN,NaN,NaN
20,0,0,1871,2.468337,NaN,NaN,NaN,NaN,NaN
21,0,0,1872,1.923452,NaN,NaN,NaN,NaN,NaN
22,0,0,1873,1.693633,NaN,NaN,NaN,NaN,NaN
23,0,0,1874,1.644746,NaN,NaN,NaN,NaN,NaN
24,0,0,1875,1.615866,NaN,NaN,NaN,NaN,NaN
25,0,0,1876,1.858038,NaN,NaN,NaN,NaN,NaN
26,0,0,1877,2.104036,NaN,NaN,NaN,NaN,NaN
27,0,0,1878,2.172756,NaN,NaN,NaN,NaN,NaN
28,0,0,1879,1.863953,NaN,NaN,NaN,NaN,NaN
29,0,0,1880,1.822373,NaN,NaN,NaN,NaN,NaN
30,0,0,1881,1.738866,NaN,NaN,NaN,NaN,NaN
31,0,0,1882,1.744259,NaN,NaN,NaN,NaN,NaN
32,0,0,1883,2.195372,NaN,NaN,NaN,NaN,NaN
33,0,0,1884,2.842380,NaN,NaN,NaN,NaN,NaN
34,0,0,1885,2.469729,1.927702,1.927702,NaN,NaN,NaN
35,0,0,1886,1.708594,1.928547,1.928547,NaN,NaN,NaN
36,0,0,1887,1.712770,1.952704,1.952704,NaN,NaN,NaN
37,0,0,1888,1.594468,1.975892,1.975892,NaN,NaN,NaN
38,0,0,1889,1.729471,1.988195,1.988195,NaN,NaN,NaN
39,0,0,1890,2.068720,1.981062,1.981062,NaN,NaN,NaN
40,0,0,1891,2.448678,1.987474,1.987474,NaN,NaN,NaN
41,0,0,1892,2.717641,2.023312,2.023312,1.975507,NaN,NaN
42,0,0,1893,2.082811,2.049160,2.049160,1.988853,NaN,NaN
43,0,0,1894,1.879088,2.059350,2.059350,2.006027,NaN,NaN
44,0,0,1895,1.842728,2.076847,2.076847,2.026369,NaN,NaN
45,0,0,1896,1.766527,2.092653,2.092653,2.040424,NaN,NaN
46,0,0,1897,2.013048,2.103962,2.103962,2.042512,NaN,NaN
47,0,0,1898,2.643006,2.101650,2.101650,2.044562,NaN,NaN
48,0,0,1899,2.744433,2.051198,2.051198,2.037255,2.000737,NaN
49,0,0,1900,1.982081,2.039094,2.039094,2.044127,2.005600,NaN
50,0,0,1901,1.754697,2.010687,2.010687,2.035018,2.007580,NaN
51,0,0,1902,1.639353,1.985187,1.985187,2.031017,2.012642,NaN
52,0,0,1903,1.653793,1.955686,1.955686,2.024170,2.012178,NaN
53,0,0,1904,1.867084,1.951337,1.951337,2.027649,2.012120,NaN
54,0,0,1905,2.278010,1.901158,1.901158,2.001404,1.996761,NaN
55,0,0,1906,2.584377,1.858932,1.858932,1.955065,1.977814,1.965286
56,0,0,1907,1.951461,1.850432,1.850432,1.944763,1.979562,1.966808
57,0,0,1908,1.755045,1.868824,1.868824,1.939755,1.979620,1.972891
58,0,0,1909,1.715901,1.882270,1.882270,1.933729,1.981435,1.980049
59,0,0,1910,1.649095,1.900611,1.900611,1.928149,1.982984,1.984286

In [20]:
agg_df.drop(["demand","window7_mean"],axis=1,inplace=True)

In [21]:
agg_df.head(2)

,state_id,cat_id,d,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28
0,0,0,1851,NaN,NaN,NaN,NaN
1,0,0,1852,NaN,NaN,NaN,NaN

In [22]:
data.head(2)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,wm_yr_wk,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,8.26
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,11604,NaN,NaN,NaN,NaN,0,0,0,3.97

In [27]:
data = data.merge(agg_df, on=["cat_id","state_id","d"],how="left")

In [28]:
data.head(2)

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,...,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,...,NaN,NaN,0,0,0,8.26,NaN,NaN,NaN,NaN
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,...,NaN,NaN,0,0,0,3.97,NaN,NaN,NaN,NaN

In [12]:
agg_df["state_id"].value_counts()

2    273
1    273
0    273
Name: state_id, dtype: int64

In [13]:
agg_df["cat_id"].value_counts()

2    273
1    273
0    273
Name: cat_id, dtype: int64

In [29]:
data.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,...,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,...,NaN,NaN,0,0,0,8.26,NaN,NaN,NaN,NaN
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,...,NaN,NaN,0,0,0,3.97,NaN,NaN,NaN,NaN
2,HOBBIES_1_003_CA_1_validation,1439,3,1,0,0,1851,0,train,2016-02-22,...,NaN,NaN,0,0,0,2.97,NaN,NaN,NaN,NaN
3,HOBBIES_1_004_CA_1_validation,1440,3,1,0,0,1851,2,train,2016-02-22,...,NaN,NaN,0,0,0,4.64,NaN,NaN,NaN,NaN
4,HOBBIES_1_005_CA_1_validation,1441,3,1,0,0,1851,0,train,2016-02-22,...,NaN,NaN,0,0,0,2.88,NaN,NaN,NaN,NaN

In [31]:
data = add_time_features(data, dt_col).pipe(reduce_mem_usage)

days finish

In [36]:
data.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,wm_yr_wk,snap_CA,snap_TX,snap_WI,sell_price,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28,year,quarter,month,week,day,dayofweek,is_year_end,is_quarter_end,is_quarter_start,is_month_end,is_month_start,is_weekend,public_holiday,eventday,NFL,Ramadan
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,11604,0,0,0,8.26,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,3.97,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,1439,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,2.97,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,1440,3,1,0,0,1851,2,train,2016-02-22,11604,0,0,0,4.64,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,1441,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,2.88,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0

In [38]:
agg_df = data.groupby(["state_id", "cat_id", "dayofweek", "d"])["demand"].mean().reset_index()

In [39]:
agg_df

     state_id  cat_id  dayofweek     d    demand
0           0       0          0  1851  1.821329
1           0       0          0  1858  1.827244
2           0       0          0  1865  2.008177
3           0       0          0  1872  1.923452
4           0       0          0  1879  1.863953
..        ...     ...        ...   ...       ...
814         2       2          6  1913  1.013372
815         2       2          6  1920  0.000000
816         2       2          6  1927  0.000000
817         2       2          6  1934  0.000000
818         2       2          6  1941  0.000000

[819 rows x 5 columns]

In [ ]:
for window in tqdm([4, 8, 12]):
        agg_df[f"state_cat_dayofweek_demand_rolling_mean_window{window}"] = agg_df.groupby(["state_id","cat_id","dayofweek"])["demand"].transform(
            lambda x: x.shift(4).rolling(window).mean()
        )

In [46]:
pd.set_option('display.max_rows', 500)

In [50]:
agg_df.head(500)

,state_id,cat_id,dayofweek,d,demand,state_cat_dayofweek_demand_rolling_mean_window4,state_cat_dayofweek_demand_rolling_mean_window8,state_cat_dayofweek_demand_rolling_mean_window12
0,0,0,0,1851,1.821329,NaN,NaN,NaN
1,0,0,0,1858,1.827244,NaN,NaN,NaN
2,0,0,0,1865,2.008177,NaN,NaN,NaN
3,0,0,0,1872,1.923452,NaN,NaN,NaN
4,0,0,0,1879,1.863953,NaN,NaN,NaN
5,0,0,0,1886,1.708594,NaN,NaN,NaN
6,0,0,0,1893,2.082811,NaN,NaN,NaN
7,0,0,0,1900,1.982081,NaN,NaN,NaN
8,0,0,0,1907,1.951461,NaN,NaN,NaN
9,0,0,0,1914,0.000000,NaN,NaN,NaN
10,0,0,0,1921,0.000000,NaN,NaN,NaN
11,0,0,0,1928,0.000000,NaN,NaN,NaN
12,0,0,0,1935,0.000000,NaN,NaN,NaN
13,0,0,1,1852,1.652053,NaN,NaN,NaN
14,0,0,1,1859,1.821155,NaN,NaN,NaN
15,0,0,1,1866,1.892484,NaN,NaN,NaN
16,0,0,1,1873,1.693633,NaN,NaN,NaN
17,0,0,1,1880,1.822373,NaN,NaN,NaN
18,0,0,1,1887,1.712770,NaN,NaN,NaN
19,0,0,1,1894,1.879088,NaN,NaN,NaN
20,0,0,1,1901,1.754697,NaN,NaN,NaN
21,0,0,1,1908,1.755045,NaN,NaN,NaN
22,0,0,1,1915,0.000000,NaN,NaN,NaN
23,0,0,1,1922,0.000000,NaN,NaN,NaN
24,0,0,1,1929,0.000000,NaN,NaN,NaN
25,0,0,1,1936,0.000000,NaN,NaN,NaN
26,0,0,2,1853,1.538448,NaN,NaN,NaN
27,0,0,2,1860,1.700765,NaN,NaN,NaN
28,0,0,2,1867,1.823243,NaN,NaN,NaN
29,0,0,2,1874,1.644746,NaN,NaN,NaN
30,0,0,2,1881,1.738866,NaN,NaN,NaN
31,0,0,2,1888,1.594468,NaN,NaN,NaN
32,0,0,2,1895,1.842728,NaN,NaN,NaN
33,0,0,2,1902,1.639353,NaN,NaN,NaN
34,0,0,2,1909,1.715901,NaN,NaN,NaN
35,0,0,2,1916,0.000000,NaN,NaN,NaN
36,0,0,2,1923,0.000000,NaN,NaN,NaN
37,0,0,2,1930,0.000000,NaN,NaN,NaN
38,0,0,2,1937,0.000000,NaN,NaN,NaN
39,0,0,3,1854,1.625609,NaN,NaN,NaN
40,0,0,3,1861,1.711726,NaN,NaN,NaN
41,0,0,3,1868,1.822373,NaN,NaN,NaN
42,0,0,3,1875,1.615866,NaN,NaN,NaN
43,0,0,3,1882,1.744259,NaN,NaN,NaN
44,0,0,3,1889,1.729471,NaN,NaN,NaN
45,0,0,3,1896,1.766527,NaN,NaN,NaN
46,0,0,3,1903,1.653793,NaN,NaN,NaN
47,0,0,3,1910,1.649095,NaN,NaN,NaN
48,0,0,3,1917,0.000000,NaN,NaN,NaN
49,0,0,3,1924,0.000000,NaN,NaN,NaN
50,0,0,3,1931,0.000000,NaN,NaN,NaN
51,0,0,3,1938,0.000000,NaN,NaN,NaN
52,0,0,4,1855,1.859255,NaN,NaN,NaN
53,0,0,4,1862,1.809325,NaN,NaN,NaN
54,0,0,4,1869,1.888483,NaN,NaN,NaN
55,0,0,4,1876,1.858038,NaN,NaN,NaN
56,0,0,4,1883,2.195372,NaN,NaN,NaN
57,0,0,4,1890,2.068720,NaN,NaN,NaN
58,0,0,4,1897,2.013048,NaN,NaN,NaN
59,0,0,4,1904,1.867084,NaN,NaN,NaN
60,0,0,4,1911,1.912143,NaN,NaN,NaN
61,0,0,4,1918,0.000000,NaN,NaN,NaN
62,0,0,4,1925,0.000000,NaN,NaN,NaN
63,0,0,4,1932,0.000000,NaN,NaN,NaN
64,0,0,4,1939,0.000000,NaN,NaN,NaN
65,0,0,5,1856,2.426583,NaN,NaN,NaN
66,0,0,5,1863,2.471468,NaN,NaN,NaN
67,0,0,5,1870,2.455289,NaN,NaN,NaN
68,0,0,5,1877,2.104036,NaN,NaN,NaN
69,0,0,5,1884,2.842380,NaN,NaN,NaN
70,0,0,5,1891,2.448678,NaN,NaN,NaN
71,0,0,5,1898,2.643006,NaN,NaN,NaN
72,0,0,5,1905,2.278010,NaN,NaN,NaN
73,0,0,5,1912,2.408664,NaN,NaN,NaN
74,0,0,5,1919,0.000000,NaN,NaN,NaN
75,0,0,5,1926,0.000000,NaN,NaN,NaN
76,0,0,5,1933,0.000000,NaN,NaN,NaN
77,0,0,5,1940,0.000000,NaN,NaN,NaN
78,0,0,6,1857,2.570633,NaN,NaN,NaN
79,0,0,6,1864,2.821503,NaN,NaN,NaN
80,0,0,6,1871,2.468337,NaN,NaN,NaN
81,0,0,6,1878,2.172756,NaN,NaN,NaN
82,0,0,6,1885,2.469729,NaN,NaN,NaN
83,0,0,6,1892,2.717641,NaN,NaN,NaN
84,0,0,6,1899,2.744433,NaN,NaN,NaN
85,0,0,6,1906,2.584377,NaN,NaN,NaN
86,0,0,6,1913,2.575852,NaN,NaN,NaN
87,0,0,6,1920,0.000000,NaN,NaN,NaN
88,0,0,6,1927,0.000000,NaN,NaN,NaN
89,0,0,6,1934,0.000000,NaN,NaN,NaN
90,0,0,6,1941,0.000000,NaN,NaN,NaN
91,0,1,0,1851,0.814602,NaN,NaN,NaN
92,0,1,0,1858,0.689381,NaN,NaN,NaN
93,0,1,0,1865,0.748673,NaN,NaN,NaN
94,0,1,0,1872,0.767257,NaN,NaN,NaN
95,0,1,0,1879,0.757965,NaN,NaN,NaN
96,0,1,0,1886,0.776106,NaN,NaN,NaN
97,0,1,0,1893,0.753540,NaN,NaN,NaN
98,0,1,0,1900,0.792478,NaN,NaN,NaN
99,0,1,0,1907,0.754867,NaN,NaN,NaN
100,0,1,0,1914,0.000000,NaN,NaN,NaN
101,0,1,0,1921,0.000000,NaN,NaN,NaN
102,0,1,0,1928,0.000000,NaN,NaN,NaN
103,0,1,0,1935,0.000000,NaN,NaN,NaN
104,0,1,1,1852,0.699558,NaN,NaN,NaN
105,0,1,1,1859,0.773451,NaN,NaN,NaN
106,0,1,1,1866,0.734956,NaN,NaN,NaN
107,0,1,1,1873,0.741150,NaN,NaN,NaN
108,0,1,1,1880,0.689381,NaN,NaN,NaN
109,0,1,1,1887,0.805752,NaN,NaN,NaN
110,0,1,1,1894,0.790265,NaN,NaN,NaN
111,0,1,1,1901,0.654425,NaN,NaN,NaN
112,0,1,1,1908,0.818142,NaN,NaN,NaN
113,0,1,1,1915,0.000000,NaN,NaN,NaN
114,0,1,1,1922,0.000000,NaN,NaN,NaN
115,0,1,1,1929,0.000000,NaN,NaN,NaN
116,0,1,1,1936,0.000000,NaN,NaN,NaN
117,0,1,2,1853,0.734513,NaN,NaN,NaN
118,0,1,2,1860,0.830973,NaN,NaN,NaN
119,0,1,2,1867,0.703540,NaN,NaN,NaN
120,0,1,2,1874,0.813274,NaN,NaN,NaN
121,0,1,2,1881,0.736283,NaN,NaN,NaN
122,0,1,2,1888,0.737168,NaN,NaN,NaN
123,0,1,2,1895,0.734071,NaN,NaN,NaN
124,0,1,2,1902,0.699115,NaN,NaN,NaN
125,0,1,2,1909,0.728319,NaN,NaN,NaN
126,0,1,2,1916,0.000000,NaN,NaN,NaN
127,0,1,2,1923,0.000000,NaN,NaN,NaN
128,0,1,2,1930,0.000000,NaN,NaN,NaN
129,0,1,2,1937,0.000000,NaN,NaN,NaN
130,0,1,3,1854,0.711062,NaN,NaN,NaN
131,0,1,3,1861,0.801770,NaN,NaN,NaN
132,0,1,3,1868,0.818142,NaN,NaN,NaN
133,0,1,3,1875,0.681858,NaN,NaN,NaN
134,0,1,3,1882,0.729646,NaN,NaN,NaN
135,0,1,3,1889,0.714159,NaN,NaN,NaN
136,0,1,3,1896,0.699115,NaN,NaN,NaN
137,0,1,3,1903,0.825664,NaN,NaN,NaN
138,0,1,3,1910,0.703540,NaN,NaN,NaN
139,0,1,3,1917,0.000000,NaN,NaN,NaN
140,0,1,3,1924,0.000000,NaN,NaN,NaN
141,0,1,3,1931,0.000000,NaN,NaN,NaN
142,0,1,3,1938,0.000000,NaN,NaN,NaN
143,0,1,4,1855,0.837611,NaN,NaN,NaN
144,0,1,4,1862,0.824336,NaN,NaN,NaN
145,0,1,4,1869,0.699115,NaN,NaN,NaN
146,0,1,4,1876,0.873894,NaN,NaN,NaN
147,0,1,4,1883,0.818142,NaN,NaN,NaN
148,0,1,4,1890,1.016372,NaN,NaN,NaN
149,0,1,4,1897,0.812832,NaN,NaN,NaN
150,0,1,4,1904,0.733628,NaN,NaN,NaN
151,0,1,4,1911,0.891593,NaN,NaN,NaN
152,0,1,4,1918,0.000000,NaN,NaN,NaN
153,0,1,4,1925,0.000000,NaN,NaN,NaN
154,0,1,4,1932,0.000000,NaN,NaN,NaN
155,0,1,4,1939,0.000000,NaN,NaN,NaN
156,0,1,5,1856,0.937168,NaN,NaN,NaN
157,0,1,5,1863,1.015929,NaN,NaN,NaN
158,0,1,5,1870,1.094690,NaN,NaN,NaN
159,0,1,5,1877,0.912832,NaN,NaN,NaN
160,0,1,5,1884,0.901770,NaN,NaN,NaN
161,0,1,5,1891,0.962832,NaN,NaN,NaN
162,0,1,5,1898,0.952212,NaN,NaN,NaN
163,0,1,5,1905,0.962832,NaN,NaN,NaN
164,0,1,5,1912,1.047345,NaN,NaN,NaN
165,0,1,5,1919,0.000000,NaN,NaN,NaN
166,0,1,5,1926,0.000000,NaN,NaN,NaN
167,0,1,5,1933,0.000000,NaN,NaN,NaN
168,0,1,5,1940,0.000000,NaN,NaN,NaN
169,0,1,6,1857,1.113274,NaN,NaN,NaN
170,0,1,6,1864,1.132301,NaN,NaN,NaN
171,0,1,6,1871,0.911062,NaN,NaN,NaN
172,0,1,6,1878,0.801770,NaN,NaN,NaN
173,0,1,6,1885,0.805310,NaN,NaN,NaN
174,0,1,6,1892,1.084513,NaN,NaN,NaN
175,0,1,6,1899,0.951770,NaN,NaN,NaN
176,0,1,6,1906,1.030973,NaN,NaN,NaN
177,0,1,6,1913,1.042920,NaN,NaN,NaN
178,0,1,6,1920,0.000000,NaN,NaN,NaN
179,0,1,6,1927,0.000000,NaN,NaN,NaN
180,0,1,6,1934,0.000000,NaN,NaN,NaN
181,0,1,6,1941,0.000000,NaN,NaN,NaN
182,0,2,0,1851,0.945320,NaN,NaN,NaN
183,0,2,0,1858,0.995941,NaN,NaN,NaN
184,0,2,0,1865,0.934336,NaN,NaN,NaN
185,0,2,0,1872,0.971347,NaN,NaN,NaN
186,0,2,0,1879,0.982330,NaN,NaN,NaN
187,0,2,0,1886,0.932904,NaN,NaN,NaN
188,0,2,0,1893,1.078797,NaN,NaN,NaN
189,0,2,0,1900,1.028176,NaN,NaN,NaN
190,0,2,0,1907,0.985912,NaN,NaN,NaN
191,0,2,0,1914,0.000000,NaN,NaN,NaN
192,0,2,0,1921,0.000000,NaN,NaN,NaN
193,0,2,0,1928,0.000000,NaN,NaN,NaN
194,0,2,0,1935,0.000000,NaN,NaN,NaN
195,0,2,1,1852,0.845033,NaN,NaN,NaN
196,0,2,1,1859,0.974451,NaN,NaN,NaN
197,0,2,1,1866,0.846227,NaN,NaN,NaN
198,0,2,1,1873,0.869389,NaN,NaN,NaN
199,0,2,1,1880,0.847182,NaN,NaN,NaN
200,0,2,1,1887,0.872254,NaN,NaN,NaN
201,0,2,1,1894,0.909503,NaN,NaN,NaN
202,0,2,1,1901,0.866046,NaN,NaN,NaN
203,0,2,1,1908,0.918577,NaN,NaN,NaN
204,0,2,1,1915,0.000000,NaN,NaN,NaN
205,0,2,1,1922,0.000000,NaN,NaN,NaN
206,0,2,1,1929,0.000000,NaN,NaN,NaN
207,0,2,1,1936,0.000000,NaN,NaN,NaN
208,0,2,2,1853,0.821394,NaN,NaN,NaN
209,0,2,2,1860,0.898042,NaN,NaN,NaN
210,0,2,2,1867,0.829513,NaN,NaN,NaN
211,0,2,2,1874,0.839303,NaN,NaN,NaN
212,0,2,2,1881,0.831423,NaN,NaN,NaN
213,0,2,2,1888,0.840735,NaN,NaN,NaN
214,0,2,2,1895,0.849093,NaN,NaN,NaN
215,0,2,2,1902,0.862225,NaN,NaN,NaN
216,0,2,2,1909,0.868911,NaN,NaN,NaN
217,0,2,2,1916,0.000000,NaN,NaN,NaN
218,0,2,2,1923,0.000000,NaN,NaN,NaN
219,0,2,2,1930,0.000000,NaN,NaN,NaN
220,0,2,2,1937,0.000000,NaN,NaN,NaN
221,0,2,3,1854,0.851480,NaN,NaN,NaN
222,0,2,3,1861,0.947947,NaN,NaN,NaN
223,0,2,3,1868,0.838348,NaN,NaN,NaN
224,0,2,3,1875,0.803964,NaN,NaN,NaN
225,0,2,3,1882,0.848376,NaN,NaN,NaN
226,0,2,3,1889,0.966094,NaN,NaN,NaN
227,0,2,3,1896,0.889446,NaN,NaN,NaN
228,0,2,3,1903,0.882760,NaN,NaN,NaN
229,0,2,3,1910,0.816380,NaN,NaN,NaN
230,0,2,3,1917,0.000000,NaN,NaN,NaN
231,0,2,3,1924,0.000000,NaN,NaN,NaN
232,0,2,3,1931,0.000000,NaN,NaN,NaN
233,0,2,3,1938,0.000000,NaN,NaN,NaN
234,0,2,4,1855,0.899236,NaN,NaN,NaN
235,0,2,4,1862,0.914995,NaN,NaN,NaN
236,0,2,4,1869,0.916905,NaN,NaN,NaN
237,0,2,4,1876,0.957259,NaN,NaN,NaN
238,0,2,4,1883,1.009074,NaN,NaN,NaN
239,0,2,4,1890,1.130372,NaN,NaN,NaN
240,0,2,4,1897,1.028176,NaN,NaN,NaN
241,0,2,4,1904,0.922875,NaN,NaN,NaN
242,0,2,4,1911,0.976361,NaN,NaN,NaN
243,0,2,4,1918,0.000000,NaN,NaN,NaN
244,0,2,4,1925,0.000000,NaN,NaN,NaN
245,0,2,4,1932,0.000000,NaN,NaN,NaN
246,0,2,4,1939,0.000000,NaN,NaN,NaN
247,0,2,5,1856,1.308500,NaN,NaN,NaN
248,0,2,5,1863,1.318052,NaN,NaN,NaN
249,0,2,5,1870,1.415473,NaN,NaN,NaN
250,0,2,5,1877,1.132521,NaN,NaN,NaN
251,0,2,5,1884,1.292025,NaN,NaN,NaN
252,0,2,5,1891,1.413563,NaN,NaN,NaN
253,0,2,5,1898,1.424785,NaN,NaN,NaN
254,0,2,5,1905,1.264088,NaN,NaN,NaN
255,0,2,5,1912,1.342407,NaN,NaN,NaN
256,0,2,5,1919,0.000000,NaN,NaN,NaN
257,0,2,5,1926,0.000000,NaN,NaN,NaN
258,0,2,5,1933,0.000000,NaN,NaN,NaN
259,0,2,5,1940,0.000000,NaN,NaN,NaN
260,0,2,6,1857,1.400430,NaN,NaN,NaN
261,0,2,6,1864,1.539398,NaN,NaN,NaN
262,0,2,6,1871,1.358644,NaN,NaN,NaN
263,0,2,6,1878,1.222541,NaN,NaN,NaN
264,0,2,6,1885,1.260745,NaN,NaN,NaN
265,0,2,6,1892,1.553247,NaN,NaN,NaN
266,0,2,6,1899,1.465377,NaN,NaN,NaN
267,0,2,6,1906,1.396132,NaN,NaN,NaN
268,0,2,6,1913,1.438395,NaN,NaN,NaN
269,0,2,6,1920,0.000000,NaN,NaN,NaN
270,0,2,6,1927,0.000000,NaN,NaN,NaN
271,0,2,6,1934,0.000000,NaN,NaN,NaN
272,0,2,6,1941,0.000000,NaN,NaN,NaN
273,1,0,0,1851,1.493389,NaN,NaN,NaN
274,1,0,0,1858,1.409186,NaN,NaN,NaN
275,1,0,0,1865,1.813964,NaN,NaN,NaN
276,1,0,0,1872,1.806541,NaN,NaN,NaN
277,1,0,0,1879,1.501508,NaN,NaN,NaN
278,1,0,0,1886,1.527488,NaN,NaN,NaN
279,1,0,0,1893,1.550220,NaN,NaN,NaN
280,1,0,0,1900,1.678961,NaN,NaN,NaN
281,1,0,0,1907,1.585247,NaN,NaN,NaN
282,1,0,0,1914,0.000000,NaN,NaN,NaN
283,1,0,0,1921,0.000000,NaN,NaN,NaN
284,1,0,0,1928,0.000000,NaN,NaN,NaN
285,1,0,0,1935,0.000000,NaN,NaN,NaN
286,1,0,1,1852,1.363953,NaN,NaN,NaN
287,1,0,1,1859,1.574577,NaN,NaN,NaN
288,1,0,1,1866,1.486662,NaN,NaN,NaN
289,1,0,1,1873,1.778010,NaN,NaN,NaN
290,1,0,1,1880,1.484806,NaN,NaN,NaN
291,1,0,1,1887,1.208768,NaN,NaN,NaN
292,1,0,1,1894,1.588495,NaN,NaN,NaN
293,1,0,1,1901,1.613083,NaN,NaN,NaN
294,1,0,1,1908,1.639063,NaN,NaN,NaN
295,1,0,1,1915,0.000000,NaN,NaN,NaN
296,1,0,1,1922,0.000000,NaN,NaN,NaN
297,1,0,1,1929,0.000000,NaN,NaN,NaN
298,1,0,1,1936,0.000000,NaN,NaN,NaN
299,1,0,2,1853,1.415681,NaN,NaN,NaN
300,1,0,2,1860,1.462770,NaN,NaN,NaN
301,1,0,2,1867,1.371839,NaN,NaN,NaN
302,1,0,2,1874,1.568314,NaN,NaN,NaN
303,1,0,2,1881,1.493389,NaN,NaN,NaN
304,1,0,2,1888,1.260496,NaN,NaN,NaN
305,1,0,2,1895,1.574809,NaN,NaN,NaN
306,1,0,2,1902,1.495245,NaN,NaN,NaN
307,1,0,2,1909,1.447924,NaN,NaN,NaN
308,1,0,2,1916,0.000000,NaN,NaN,NaN
309,1,0,2,1923,0.000000,NaN,NaN,NaN
310,1,0,2,1930,0.000000,NaN,NaN,NaN
311,1,0,2,1937,0.000000,NaN,NaN,NaN
312,1,0,3,1854,1.378566,NaN,NaN,NaN
313,1,0,3,1861,1.683600,NaN,NaN,NaN
314,1,0,3,1868,1.560195,NaN,NaN,NaN
315,1,0,3,1875,1.502900,NaN,NaN,NaN
316,1,0,3,1882,1.392948,NaN,NaN,NaN
317,1,0,3,1889,1.329390,NaN,NaN,NaN
318,1,0,3,1896,1.606124,NaN,NaN,NaN
319,1,0,3,1903,1.534447,NaN,NaN,NaN
320,1,0,3,1910,1.430527,NaN,NaN,NaN
321,1,0,3,1917,0.000000,NaN,NaN,NaN
322,1,0,3,1924,0.000000,NaN,NaN,NaN
323,1,0,3,1931,0.000000,NaN,NaN,NaN
324,1,0,3,1938,0.000000,NaN,NaN,NaN
325,1,0,4,1855,1.411969,NaN,NaN,NaN
326,1,0,4,1862,1.506611,NaN,NaN,NaN
327,1,0,4,1869,1.708884,NaN,NaN,NaN
328,1,0,4,1876,1.628624,NaN,NaN,NaN
329,1,0,4,1883,1.927627,NaN,NaN,NaN
330,1,0,4,1890,1.742751,NaN,NaN,NaN
331,1,0,4,1897,1.606124,NaN,NaN,NaN
332,1,0,4,1904,1.622361,NaN,NaN,NaN
333,1,0,4,1911,1.586407,NaN,NaN,NaN
334,1,0,4,1918,0.000000,NaN,NaN,NaN
335,1,0,4,1925,0.000000,NaN,NaN,NaN
336,1,0,4,1932,0.000000,NaN,NaN,NaN
337,1,0,4,1939,0.000000,NaN,NaN,NaN
338,1,0,5,1856,1.681744,NaN,NaN,NaN
339,1,0,5,1863,1.853398,NaN,NaN,NaN
340,1,0,5,1870,1.932730,NaN,NaN,NaN
341,1,0,5,1877,1.713987,NaN,NaN,NaN
342,1,0,5,1884,2.108096,NaN,NaN,NaN
343,1,0,5,1891,1.855022,NaN,NaN,NaN
344,1,0,5,1898,2.036650,NaN,NaN,NaN
345,1,0,5,1905,1.842728,NaN,NaN,NaN
346,1,0,5,1912,1.820691,NaN,NaN,NaN
347,1,0,5,1919,0.000000,NaN,NaN,NaN
348,1,0,5,1926,0.000000,NaN,NaN,NaN
349,1,0,5,1933,0.000000,NaN,NaN,NaN
350,1,0,5,1940,0.000000,NaN,NaN,NaN
351,1,0,6,1857,1.905590,NaN,NaN,NaN
352,1,0,6,1864,2.099513,NaN,NaN,NaN
353,1,0,6,1871,2.066342,NaN,NaN,NaN
354,1,0,6,1878,1.967525,NaN,NaN,NaN
355,1,0,6,1885,2.163071,NaN,NaN,NaN
356,1,0,6,1892,2.116910,NaN,NaN,NaN
357,1,0,6,1899,2.090930,NaN,NaN,NaN
358,1,0,6,1906,2.022037,NaN,NaN,NaN
359,1,0,6,1913,1.801206,NaN,NaN,NaN
360,1,0,6,1920,0.000000,NaN,NaN,NaN
361,1,0,6,1927,0.000000,NaN,NaN,NaN
362,1,0,6,1934,0.000000,NaN,NaN,NaN
363,1,0,6,1941,0.000000,NaN,NaN,NaN
364,1,1,0,1851,0.633038,NaN,NaN,NaN
365,1,1,0,1858,0.558112,NaN,NaN,NaN
366,1,1,0,1865,0.531563,NaN,NaN,NaN
367,1,1,0,1872,0.624189,NaN,NaN,NaN
368,1,1,0,1879,0.487316,NaN,NaN,NaN
369,1,1,0,1886,0.542773,NaN,NaN,NaN
370,1,1,0,1893,0.589381,NaN,NaN,NaN
371,1,1,0,1900,0.663717,NaN,NaN,NaN
372,1,1,0,1907,0.489676,NaN,NaN,NaN
373,1,1,0,1914,0.000000,NaN,NaN,NaN
374,1,1,0,1921,0.000000,NaN,NaN,NaN
375,1,1,0,1928,0.000000,NaN,NaN,NaN
376,1,1,0,1935,0.000000,NaN,NaN,NaN
377,1,1,1,1852,0.515634,NaN,NaN,NaN
378,1,1,1,1859,0.653097,NaN,NaN,NaN
379,1,1,1,1866,0.521534,NaN,NaN,NaN
380,1,1,1,1873,0.618879,NaN,NaN,NaN
381,1,1,1,1880,0.523304,NaN,NaN,NaN
382,1,1,1,1887,0.489086,NaN,NaN,NaN
383,1,1,1,1894,0.516224,NaN,NaN,NaN
384,1,1,1,1901,0.616519,NaN,NaN,NaN
385,1,1,1,1908,0.604720,NaN,NaN,NaN
386,1,1,1,1915,0.000000,NaN,NaN,NaN
387,1,1,1,1922,0.000000,NaN,NaN,NaN
388,1,1,1,1929,0.000000,NaN,NaN,NaN
389,1,1,1,1936,0.000000,NaN,NaN,NaN
390,1,1,2,1853,0.530383,NaN,NaN,NaN
391,1,1,2,1860,0.551032,NaN,NaN,NaN
392,1,1,2,1867,0.466667,NaN,NaN,NaN
393,1,1,2,1874,0.559882,NaN,NaN,NaN
394,1,1,2,1881,0.653097,NaN,NaN,NaN
395,1,1,2,1888,0.560472,NaN,NaN,NaN
396,1,1,2,1895,0.588791,NaN,NaN,NaN
397,1,1,2,1902,0.599410,NaN,NaN,NaN
398,1,1,2,1909,0.578171,NaN,NaN,NaN
399,1,1,2,1916,0.000000,NaN,NaN,NaN
400,1,1,2,1923,0.000000,NaN,NaN,NaN
401,1,1,2,1930,0.000000,NaN,NaN,NaN
402,1,1,2,1937,0.000000,NaN,NaN,NaN
403,1,1,3,1854,0.519764,NaN,NaN,NaN
404,1,1,3,1861,0.591740,NaN,NaN,NaN
405,1,1,3,1868,0.555162,NaN,NaN,NaN
406,1,1,3,1875,0.583481,NaN,NaN,NaN
407,1,1,3,1882,0.538643,NaN,NaN,NaN
408,1,1,3,1889,0.517994,NaN,NaN,NaN
409,1,1,3,1896,0.588791,NaN,NaN,NaN
410,1,1,3,1903,0.622419,NaN,NaN,NaN
411,1,1,3,1910,0.520354,NaN,NaN,NaN
412,1,1,3,1917,0.000000,NaN,NaN,NaN
413,1,1,3,1924,0.000000,NaN,NaN,NaN
414,1,1,3,1931,0.000000,NaN,NaN,NaN
415,1,1,3,1938,0.000000,NaN,NaN,NaN
416,1,1,4,1855,0.641298,NaN,NaN,NaN
417,1,1,4,1862,0.558702,NaN,NaN,NaN
418,1,1,4,1869,0.450147,NaN,NaN,NaN
419,1,1,4,1876,0.530383,NaN,NaN,NaN
420,1,1,4,1883,0.611209,NaN,NaN,NaN
421,1,1,4,1890,0.699115,NaN,NaN,NaN
422,1,1,4,1897,0.637168,NaN,NaN,NaN
423,1,1,4,1904,0.653097,NaN,NaN,NaN
424,1,1,4,1911,0.623009,NaN,NaN,NaN
425,1,1,4,1918,0.000000,NaN,NaN,NaN
426,1,1,4,1925,0.000000,NaN,NaN,NaN
427,1,1,4,1932,0.000000,NaN,NaN,NaN
428,1,1,4,1939,0.000000,NaN,NaN,NaN
429,1,1,5,1856,0.608850,NaN,NaN,NaN
430,1,1,5,1863,0.610029,NaN,NaN,NaN
431,1,1,5,1870,0.639528,NaN,NaN,NaN
432,1,1,5,1877,0.781711,NaN,NaN,NaN
433,1,1,5,1884,0.698525,NaN,NaN,NaN
434,1,1,5,1891,0.839528,NaN,NaN,NaN
435,1,1,5,1898,0.675516,NaN,NaN,NaN
436,1,1,5,1905,0.663127,NaN,NaN,NaN
437,1,1,5,1912,0.720944,NaN,NaN,NaN
438,1,1,5,1919,0.000000,NaN,NaN,NaN
439,1,1,5,1926,0.000000,NaN,NaN,NaN
440,1,1,5,1933,0.000000,NaN,NaN,NaN
441,1,1,5,1940,0.000000,NaN,NaN,NaN
442,1,1,6,1857,0.720944,NaN,NaN,NaN
443,1,1,6,1864,0.733333,NaN,NaN,NaN
444,1,1,6,1871,0.624779,NaN,NaN,NaN
445,1,1,6,1878,0.688496,NaN,NaN,NaN
446,1,1,6,1885,0.653097,NaN,NaN,NaN
447,1,1,6,1892,0.757522,NaN,NaN,NaN
448,1,1,6,1899,0.768142,NaN,NaN,NaN
449,1,1,6,1906,0.861947,NaN,NaN,NaN
450,1,1,6,1913,0.746903,NaN,NaN,NaN
451,1,1,6,1920,0.000000,NaN,NaN,NaN
452,1,1,6,1927,0.000000,NaN,NaN,NaN
453,1,1,6,1934,0.000000,NaN,NaN,NaN
454,1,1,6,1941,0.000000,NaN,NaN,NaN
455,1,2,0,1851,0.924546,NaN,NaN,NaN
456,1,2,0,1858,0.936644,NaN,NaN,NaN
457,1,2,0,1865,0.917542,NaN,NaN,NaN
458,1,2,0,1872,0.966571,NaN,NaN,NaN
459,1,2,0,1879,0.851321,NaN,NaN,NaN
460,1,2,0,1886,0.890799,NaN,NaN,NaN
461,1,2,0,1893,0.896211,NaN,NaN,NaN
462,1,2,0,1900,0.894938,NaN,NaN,NaN
463,1,2,0,1907,0.701687,NaN,NaN,NaN
464,1,2,0,1914,0.000000,NaN,NaN,NaN
465,1,2,0,1921,0.000000,NaN,NaN,NaN
466,1,2,0,1928,0.000000,NaN,NaN,NaN
467,1,2,0,1935,0.000000,NaN,NaN,NaN
468,1,2,1,1852,0.861191,NaN,NaN,NaN
469,1,2,1,1859,0.938236,NaN,NaN,NaN
470,1,2,1,1866,0.793696,NaN,NaN,NaN
471,1,2,1,1873,0.937599,NaN,NaN,NaN
472,1,2,1,1880,0.808023,NaN,NaN,NaN
473,1,2,1,1887,0.726520,NaN,NaN,NaN
474,1,2,1,1894,0.873289,NaN,NaN,NaN
475,1,2,1,1901,0.770137,NaN,NaN,NaN
476,1,2,1,1908,0.901305,NaN,NaN,NaN
477,1,2,1,1915,0.000000,NaN,NaN,NaN
478,1,2,1,1922,0.000000,NaN,NaN,NaN
479,1,2,1,1929,0.000000,NaN,NaN,NaN
480,1,2,1,1936,0.000000,NaN,NaN,NaN
481,1,2,2,1853,0.904171,NaN,NaN,NaN
482,1,2,2,1860,0.847501,NaN,NaN,NaN
483,1,2,2,1867,0.759631,NaN,NaN,NaN
484,1,2,2,1874,0.881248,NaN,NaN,NaN
485,1,2,2,1881,0.890162,NaN,NaN,NaN
486,1,2,2,1888,0.778096,NaN,NaN,NaN
487,1,2,2,1895,0.812162,NaN,NaN,NaN
488,1,2,2,1902,0.710602,NaN,NaN,NaN
489,1,2,2,1909,0.757084,NaN,NaN,NaN
490,1,2,2,1916,0.000000,NaN,NaN,NaN
491,1,2,2,1923,0.000000,NaN,NaN,NaN
492,1,2,2,1930,0.000000,NaN,NaN,NaN
493,1,2,2,1937,0.000000,NaN,NaN,NaN
494,1,2,3,1854,0.849411,NaN,NaN,NaN
495,1,2,3,1861,0.998090,NaN,NaN,NaN
496,1,2,3,1868,0.949061,NaN,NaN,NaN
497,1,2,3,1875,0.860236,NaN,NaN,NaN
498,1,2,3,1882,0.759949,NaN,NaN,NaN
499,1,2,3,1889,0.858644,NaN,NaN,NaN

In [51]:
agg_df.describe()

,state_id,cat_id,dayofweek,d,demand,state_cat_dayofweek_demand_rolling_mean_window4,state_cat_dayofweek_demand_rolling_mean_window8,state_cat_dayofweek_demand_rolling_mean_window12
count,819.000000,819.000000,819.000000,819.000000,819.000000,0.0,0.0,0.0
mean,1.000000,1.000000,3.000000,1896.000000,0.820408,NaN,NaN,NaN
std,0.816996,0.816996,2.001222,26.283902,0.747342,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,1851.000000,0.000000,NaN,NaN,NaN
25%,0.000000,0.000000,1.000000,1873.000000,0.000000,NaN,NaN,NaN
50%,1.000000,1.000000,3.000000,1896.000000,0.746903,NaN,NaN,NaN
75%,2.000000,2.000000,5.000000,1919.000000,1.257278,NaN,NaN,NaN
max,2.000000,2.000000,6.000000,1941.000000,3.331478,NaN,NaN,NaN

In [54]:
data.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand,part,date,wm_yr_wk,snap_CA,snap_TX,snap_WI,sell_price,state_cate_mean_window7,state_cate_mean_window14,state_cate_mean_window21,state_cate_mean_window28,year,quarter,month,week,day,dayofweek,is_year_end,is_quarter_end,is_quarter_start,is_month_end,is_month_start,is_weekend,public_holiday,eventday,NFL,Ramadan
0,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,1851,4,train,2016-02-22,11604,0,0,0,8.26,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,3.97,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,1439,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,2.97,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,1440,3,1,0,0,1851,2,train,2016-02-22,11604,0,0,0,4.64,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,1441,3,1,0,0,1851,0,train,2016-02-22,11604,0,0,0,2.88,NaN,NaN,NaN,NaN,2016,1,2,8,22,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
for diff in tqdm([0, 7, 14, 21, 28]):
        shift = 28 + diff
        data[f"demand_shift_t{shift}"] = data.groupby(["id"])["demand"].transform(
            lambda x: x.shift(shift)
        )

100%|██████████| 5/5 [00:52<00:00, 10.33s/it]

In [ ]:
data.head()